# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application virt env

on:
  push:
    branches: [ "main" ]
  # pull_request:
    # branches: [ "main" ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"


    - name: Install ENV
      run: |
      
        python3 -m venv venv
        source venv/bin/activate
        echo "VIRTUAL ENV:" $VIRTUAL_ENV


    - name: Install req
      run: pip install -r requirements.txt


    - name: Run the SQRTs
      run: python main.py

    - name: identify App
      run: |
        echo "Scriptul meu"

    - name: Test with pytest
      run: pytest
